### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by alekslario** [chromaui/intro-storybook-react-template#3]
`React-scripts` installs `react@"^17.0.1"` but `@reach/router@1.3.4` (dep of ` @storybook/addon-actions` latest version ) requires `react@"15.x || 16.x || 16.4.0-alpha.0911da3"` , I think it's better to lock react at earlier version

**Comment by jonniebigodes** [comment]
@alekslario we appreciate the time you took to open this issue here, but it seems that this is not technically related to this repo, but to Storybook. If you don't mind closing this and open an issue in the Storybook issue tracker, detailing in full what's happening we'd appreciate it. And if you're willing to work with us and help fix the issue, read the [contribution guidelines](https://storybook.js.org/docs/react/contribute/how-to-contribute) and we'll go from there?

Sounds good?

Stay safe
