### ISSUE TITLE
.yarn folder

### ISSUE THREAD

**Issue by siddtheone** [chromaui/intro-storybook-react-template#4]
Should we add .yarn folder to .gitignore?

**Comment by jonniebigodes** [comment]
Hi, @siddtheone it's up to you and how and which version of yarn you're using. I left it out because some of our readers might still be using yarn 1 others might be using yarn2 and didn't want to introduce any issues when using the template. Leaving it to the end reader on how he/she would like to tackle it.

Thanks for bringing this to our attention. Let us know of any issues, questions, or other feedback for the templates or tutorials. 

Stay safe
